# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_parser', '0002_auto_20160607_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyvaluepair',
            name='container',
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Dictionary',
        ),
        migrations.DeleteModel(
            name='KeyValuePair',
        ),
    ]
